name: Build and deploy WAR app to Azure Web App - geo-mot

 on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn clean package
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'geo-mot'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_53D4CF0A364B4570AFEEA9A9AC375FDC }}
          package: '${{ github.workspace }}/target/*.jar'
